### PR TITLE
Explorer tabs upgrade

### PR DESCRIPTION
**Pull request by fabiolalombardim**
* Modified existing "Proposal" tab according to Figma
* Added new "Config" tab

### CODE REVIEW

**Review by thenerdcat — APPROVED** [review]

**Comment by thenerdcat** [comment]
Approved. But on Mobile this section of the Config Page is not fully responsive  . We could create a separate task for fixing this.

**Comment by thenerdcat** [comment]
this is how it looks on mobile. the variables are not visible

**Review by Man-Jain — CHANGES_REQUESTED** [review]
Screenshot 2023-01-31 at 4 25 57 AM

This should be "Execute Lambda" - Execute a Lambda already Installed on DAO

**Review by Man-Jain — CHANGES_REQUESTED** [review]
Screenshot 2023-01-31 at 4 30 15 AM


The formula that we apply when taking input from the user and sending the values in the contract (https://github.com/dOrgTech/homebase-app/blob/b90a4a1a292e7fa75df93c3986bfdaf5a502b0ae/src/services/contracts/baseDAO/utils.ts#L14 and https://github.com/dOrgTech/homebase-app/blob/b90a4a1a292e7fa75df93c3986bfdaf5a502b0ae/src/services/contracts/baseDAO/utils.ts#L15) should be reverse engineered so we show the user the same values he put in otherwise they'll be confused.

**Review by Man-Jain — CHANGES_REQUESTED** [review]
Screenshot 2023-01-31 at 4 35 24 AM

Should show the governance Token Symbol here at the end.

**Comment by fabiolalombardim** [comment]
Captura de pantalla 2023-01-31 a las 12 55 18

Responsive tables fixed

**Review by EightRice — APPROVED** [review]

**Comment by Man-Jain** [comment]
screenshot

This should not be %age but should be 20000200000.004 <GovernanceTokenSymbol>

<details><summary>Browser metadata</summary>





```
Path:      /explorer/dao/KT1UCEscNaP7dj6FsKrGezDrxuak8b9ibHxp/config
Browser:   Firefox 109.0 on Mac OS 10.15
Viewport:  1512 x 831 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-485--tezos-homebase.netlify.app%2Fexplorer%2Fdao%2FKT1UCEscNaP7dj6FsKrGezDrxuak8b9ibHxp%2Fconfig&os=OS%20X&os_version=Catalina&browser=Firefox&browser_version=109.0&resolution=1512x831&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-485--tezos-homebase.netlify.app/explorer/dao/KT1UCEscNaP7dj6FsKrGezDrxuak8b9ibHxp/config) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=63d900886d4e720008512de7&commentID=63d99ba84348a90330145eaa&resolution=resolved)

**Comment by Man-Jain** [comment]
> Screenshot 2023-01-31 at 4 30 15 AM
> 
> The formula that we apply when taking input from the user and sending the values in the contract (
> 
> https://github.com/dOrgTech/homebase-app/blob/b90a4a1a292e7fa75df93c3986bfdaf5a502b0ae/src/services/contracts/baseDAO/utils.ts#L14
> and
> 
> https://github.com/dOrgTech/homebase-app/blob/b90a4a1a292e7fa75df93c3986bfdaf5a502b0ae/src/services/contracts/baseDAO/utils.ts#L15
> ) should be reverse engineered so we show the users the same values they put in otherwise they'll be confused.

This hasn't been resolved

**Comment by Man-Jain** [comment]
> Screenshot 2023-01-31 at 4 25 57 AM
> 
> This should be "Execute Lambda" - "Execute a Lambda already Installed on DAO"

This also hasn't been resolved

**Review by Man-Jain — APPROVED** [review]

**Pull request merged**
